name: Forja TCC Tostadora
on: [workflow_dispatch]

jobs:
  forjar:
    runs-on: ubuntu-22.04
    steps:
      - name: Instala dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y git make gcc gcc-aarch64-linux-gnu

      - name: Compila TCC estático ARM64
        run: |
          git clone --depth=1 --branch=release_0_9_27 https://repo.or.cz/tinycc.git
          cd tinycc
          ./configure --cpu=aarch64 --cross-prefix=aarch64-linux-gnu- --config-musl --prefix=/tmp/tcc --enable-static
          make -j$(nproc)
          make install
          strip /tmp/tcc/bin/tcc
          tar -czf /tmp/tcc-arm64.tar.gz -C /tmp tcc

      - name: Sube el artefacto
        uses: actions/upload-artifact@v4
        with:
          name: tcc-arm64-tostadora
          path: /tmp/tcc-arm64.tar.gz
