name: Forja TCC Tostadora
on: [workflow_dispatch]

jobs:
  forjar:
    runs-on: ubuntu-22.04
    steps:
      - name: Baja tu repo
        uses: actions/checkout@v4

      - name: Instala dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc gcc-aarch64-linux-gnu

      - name: Compila SOLO TCC estático desde TU tar
        run: |
          tar -xjf tcc-0.9.27.tar.bz2
          cd tcc-0.9.27
          ./configure --cpu=aarch64 --cross-prefix=aarch64-linux-gnu- --config-musl --enable-static --extra-ldflags=-static
          make -j$(nproc) tcc LDFLAGS=-static
          file tcc
          mv tcc ../tcc-arm64-static
          cd ..
          tar -czf tcc-arm64-static.tar.gz tcc-arm64-static

      - name: Sube el artefacto
        uses: actions/upload-artifact@v4
        with:
          name: tcc-arm64-tostadora
          path: tcc-arm64-static.tar.gz
