name: Forja de Dagas TWRP
on: [workflow_dispatch]

jobs:
  forjar:
    runs-on: ubuntu-22.04
    steps:
      - name: Clonar templo
        uses: actions/checkout@v4

      - name: Instalar armas de forja
        run: sudo apt-get update && sudo apt-get install -y gcc-multilib make

      - name: Desempacar TCC
        run: tar -xjf tcc-0.9.27.tar.bz2

      - name: Forjar TCC estático
        run: |
          cd tcc-0.9.27
          ./configure --cc=gcc --disable-bcheck --prefix=/tmp/tcc-forja
          make LDFLAGS=-static
          make install
          strip /tmp/tcc-forja/bin/tcc
          
      - name: Desempacar Plotutils
        run: tar -xzf plotutils-2.6.tar.gz

      - name: Forjar libplot.a estática
        run: |
          cd plotutils-2.6
          CC=/tmp/tcc-forja/bin/tcc ./configure --disable-shared --enable-static --without-x --prefix=/tmp/plot-forja CFLAGS=-O2
          make LDFLAGS=-static
          make install
          strip /tmp/plot-forja/lib/libplot.a
          
      - name: Empacar las dagas
        run: |
          mkdir dagas
          cp /tmp/tcc-forja/bin/tcc dagas/
          cp /tmp/plot-forja/lib/libplot.a dagas/
          tar -czf dagas-twrp.tar.gz dagas/
          
      - name: Subir dagas al altar
        uses: actions/upload-artifact@v4
        with:
          name: dagas-twrp
          path: dagas-twrp.tar.gz
